import { City } from '../models/city.model';

export const arrayOfCities: City[] = [
  {
    id: 1,
    country: {
      id: null,
      code2: 'BG',
      code3: 'BGR',
      name: 'България',
      nameEn: 'Bulgaria',
      isEU: true,
    },
    postCode: '8500',
    name: 'Айтос',
    nameEn: 'Aytos',
    regionName: 'Бургас',
    regionNameEn: 'Burgas',
    phoneCode: '558',
    location: null,
    expressCityDeliveries: true,
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: true,
    friday: true,
    saturday: true,
    sunday: false,
  },
  {
    id: 2,
    country: {
      id: null,
      code2: 'BG',
      code3: 'BGR',
      name: 'България',
      nameEn: 'Bulgaria',
      isEU: true,
    },
    postCode: '7700',
    name: 'Айтос',
    nameEn: 'Pepe',
    regionName: 'Бургас',
    regionNameEn: 'Plovdiv',
    phoneCode: '558',
    location: null,
    expressCityDeliveries: false,
    monday: true,
    tuesday: false,
    wednesday: true,
    thursday: true,
    friday: true,
    saturday: true,
    sunday: false,
  },
  {
    id: 3,
    country: {
      id: null,
      code2: 'BG',
      code3: 'BGR',
      name: 'България',
      nameEn: 'Bulgaria',
      isEU: true,
    },
    postCode: '1100',
    name: 'Айтос',
    nameEn: 'Ayuntamiento',
    regionName: 'Бургас',
    regionNameEn: 'Sofia',
    phoneCode: '558',
    location: null,
    expressCityDeliveries: true,
    monday: true,
    tuesday: true,
    wednesday: true,
    thursday: true,
    friday: true,
    saturday: true,
    sunday: false,
  },
];
